In [424]:
# This block is to split the etire route into m sub-routes
# We separte the array for the route into "From" and "To" arrays
# We derive the partion array based on the valute of the node, using "no.where()" function
# We split the "From" and "To" array, using "np.split(partition)"

# This block should be turned into a function later on

from scipy import sparse
from scipy.stats import uniform
from array import array
import numpy as np
import random

# Input variables of the functon
n=10
m=3

## One route: a list of numbers
#a=np.array(range(n+m))
#print(a)

## Genrate one route by randomly shuffle a list of numbers from 1 to n+m
#a=np.array(random.sample(range(1,n+m), n+m-1)).reshape(1,n+m-1)
np.random.seed(15)
a=np.array(random.sample(range(1,n+m), n+m-1))
print (a)
#print (a>4)
print (a.shape)
# Add the deport at the begining and end of the randomly generated route
#full=np.array(np.append(np.append([0],a),[0])).reshape(1,n+m+1)
full=np.array(np.append(np.append([0],a),[0]))
print (full)
#print (full>4)
print (full.shape)


#full=np.array(np.append(np.array(range(0,n+m)),[0]))
print("The full route is")
print(full)
print(sep='\n')

# Derive the "from" and "to" nodes based on given route
From_idx = full[:-1]
To_idx = full[1:]

print(From_idx)
print(To_idx)

# Partition the entire route base on its value
# To find the "turning point"
partition=np.asarray(np.where(full>n))[0]
print(partition)
print(partition.size)

for i in range(partition.size):
    print(partition[i])
    
print(sep='\n')

#Split=np.split(full,partition)
Split_from=np.split(From_idx,partition)
Split_to=np.split(To_idx,partition)

print("The number of the sub array is "+ str(len(Split_from)) + ".")

print("From sub route")
for i in range(len(Split_from)):
    print(Split_from[i])

print(sep='\n')
print(sep='\n')
print("To sub route")
for i in range(len(Split_to)):
    print(Split_to[i])
    

[11  2  1  9  8  5  3  7  6 10 12  4]
(12,)
[ 0 11  2  1  9  8  5  3  7  6 10 12  4  0]
(14,)
The full route is
[ 0 11  2  1  9  8  5  3  7  6 10 12  4  0]

[ 0 11  2  1  9  8  5  3  7  6 10 12  4]
[11  2  1  9  8  5  3  7  6 10 12  4  0]
[ 1 11]
2
1
11

The number of the sub array is 3.
From sub route
[0]
[11  2  1  9  8  5  3  7  6 10]
[12  4]


To sub route
[11]
[ 2  1  9  8  5  3  7  6 10 12]
[4 0]


In [2]:
# This block is to genrate the total cost matrix

# It is the sum of two sources of costs: traveling cost (none-diagnal) and work cost (diagnal)
# Any none-feasible connection between two nodes is indicated by a large distance: OnewayD

import numpy as np
import random

# Number of nodes
n=8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
# Number of salesmam
m=2
# Size of the distance matrix for 1-salesmen. 
# We add a row/col to represent the TRAVELING distance between the deport and any node.
N=n+1
# TRAVELING Distance of any node to itself
SelfD=0
# A large number to represent infeasible connection, such as one-way street
InfeasibleD=2000

# Initialize a random square matrix
# This matrix will go through the following steps to become the TRAVELING distanec matrix 
# for our n-node, m-salesmen problem
np.random.seed(2)
b=np.random.randint(0,30,size=(N,N))

# Step 1 -- Make it symmetrical
distance = (b+b.T)/2

# Step2 -- randomly asiign a few one-way street/infeasible connection 
# by making the distance between two random nodes much bigger than the distance for feasible connections
for i in range(3):
    np.random.seed(i)
    c=random.sample(range(1,len(distance)), 2)
    distance[c[0],c[1]]=InfeasibleD
    
# Step3 -- No traveling distance from any node to itself
np.fill_diagonal(distance,SelfD)
print("The initial distance matrix is")
print(distance)
print("The shape of the initial distance matrix is")
print(distance.shape)
print("The size of the initial distance matrix is")
print(distance.size)
print("The length of the initial distance matrix is")
print(len(distance))
print(sep='\n')
print(sep='\n')

######################################################################
# From this point on, we turn it into a function
# Step4 -- Extend the distance matrix for 1-salesmen to m-salesmen
# Repeat the first rows of the distance m-1 times
for i in range(m-1):
    distance = np.append(distance,distance[0:1,:], axis=0)
# Repeat the first colume of the distance m-1 times
for j in range(m-1):
    distance = np.append(distance,distance[:,0:1], axis=1)
    
# Step 5 -- Modify the extended distance matrix, 
# so that traveling among the last m-1 nodes is prohibited
distance[:1,-(m-1):]=InfeasibleD
distance[-(m-1):,:1]=InfeasibleD
distance[-(m-1):,-(m-1):]=InfeasibleD
    
#  Print the final TRAVELING distance matrix    
TravelDis=distance
print("The extended distance matrix is")
print(TravelDis)
print("The shape of the extended distance is")
print(TravelDis.shape)
print(sep='\n')
print(sep='\n')



###########################################################
# We may want to cut it off below

# Do we want to add the cost/time requirement to the disagnal of the TRAVELING distance mztrx?
# Now we have the total cost matrx
np.random.seed(2)
WorkCost=np.random.randint(0,25,size=(1,N))
print("The cost for completing the task at each node is")
print(WorkCost)
print("The shape of the work cost is")
print(WorkCost.shape)
print(sep='\n')
print(sep='\n')

# Now, adding the work cost  array to the diagnal of the distance matrix (traveling cost)
# To get the total cost matrix
np.fill_diagonal(distance[:N,:N],WorkCost)
TotalCost=distance
print("The total cost is")
print(TotalCost)
print("The shape of the total cost matrix is")
print(TotalCost.shape)

# We may want to cut it off above
###########################################################



The initial distance matrix is
[[   0.    11.    16.5    7.5   13.    11.5   18.    16.5   17. ]
 [  11.     0.    11.     8.5   17.5   16.5   19.5   22.    23.5]
 [  16.5 2000.     0.     6.5    6.     4.    18.    18.5    9.5]
 [   7.5    8.5    6.5    0.    22.5   27.     9.    13.    17.5]
 [  13.    17.5 2000.    22.5    0.     8.5   12.5   14.5    7. ]
 [  11.5   16.5    4.    27.     8.5    0.    10.    19.5   17. ]
 [  18.    19.5   18.     9.    12.5   10.     0.    16.    17.5]
 [  16.5 2000.    18.5   13.    14.5   19.5   16.     0.    18. ]
 [  17.    23.5    9.5   17.5    7.    17.    17.5   18.     0. ]]
The shape of the initial distance matrix is
(9, 9)
The size of the initial distance matrix is
81
The length of the initial distance matrix is
9


The extended distance matrix is
[[   0.    11.    16.5    7.5   13.    11.5   18.    16.5   17.  2000. ]
 [  11.     0.    11.     8.5   17.5   16.5   19.5   22.    23.5   11. ]
 [  16.5 2000.     0.     6.5    6.     4.    18. 

In [380]:
# This block is to calculate the total cost for a given route
# The algorithem truns the route into a sparse(RouteMatrx) matrix with either 0 or 1 entry
# The total cost for the route is the sum of all elements in TotalDis*RouteMatrix


# The TOTAL cost matrix and the route will be given as inputs

from scipy import sparse
from scipy.stats import uniform
from array import array
import numpy as np
import random


# The following should be input to the function
n=5
m=2


# This is a placeholder for the Total cost matrix
np.random.seed(2)
TotalDis=np.random.randint(0,30,size=(n+1,n+1))
print(TotalDis)
print(sep='\n')
print(len(TotalDis))
print(sep='\n')

# This is a placeholder for the route
# The input of the function should be "Route", "a" is the intermediate step
a=np.array(random.sample(range(1,n), n-2))
#print(a)
#print(sep='\n')

#Route=np.array(np.append(np.append([0],a),[0]).reshape(n))
# "Route" will become a input
# You need to make sure that the "0" at the begining and the end of the route are added
# Before passing to this function
Route=np.array(np.append(np.append([0],a),[0]))
print(Route)
print(Route.size)
print(sep='\n')


# Initialize the route indicator matrix
# Use the size of the distance matrix to initialize the indocator matrix
RouteIndicator=np.zeros((len(TotalDis),len(TotalDis)))

# Split teh given route array, into the "from" array, and the "to" array
row_ind=Route[:-1]
col_ind=Route[1:]
print(row_ind)
print(col_ind)
print(sep='\n')


# Update the RouteIndicator matrix so that the nodes are part of the given route has value=1
RouteIndicator[row_ind,col_ind]=1
print(RouteIndicator)
print(sep='\n')

#RouteCost=np.sum(TotalDis*mat_coo.toarray())
RouteCost=np.sum(TotalDis*RouteIndicator)
print(RouteCost)
print(sep='\n')


[[ 8 15 13  8 22 11]
 [18 11  8  7  2 17]
 [11 21 15 26 20 28]
 [20  5  7  3  6  4]
 [10 11 19  7  6 10]
 [ 1 26 28  3  5 24]]

6

[4 1 3]

[0 4 1 3 0]
5

[0 4 1 3]
[4 1 3 0]

[[0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

60.0



In [466]:
# This bloack is demonstrate:
# Given one complete route, how to split it into m sub-routes based on its value 
# The store the complte route and its subroutes in an array of arrays
# How to generate an indicator matrx of matrices for each route in the above array using for-loop 

from scipy import sparse
from scipy.stats import uniform
from array import array
import numpy as np
import random


# Assume 3 cities
n=3

# Assume 2 salesman
m=2
# Distance matrix, should be an input variable
np.random.seed(2)
Dis=np.random.randint(0,30,size=(n+1,n+1))
print(TotalDis)
print(sep='\n')

Route=np.array([0,2,1,3,0])
Route_From=Route[:-1]
Route_To=Route[1:]
print("The combined route travels from nodes")
print(Route_From)
print("The combined route travels to nodes")
print(Route_To)
print(sep='\n')

# partition=np.array([1,2])
# Use np.where to set partition location
# In actual implementation, the criteria would be "Route>n"
#partition=np.array([1,2])
partition=np.asarray(np.where(Route>1))[0]
# ues np.split to split the route into subroutes
Split_From=np.split(Route_From,partition)
# Add the subroutes after the combined route
Split_From.insert(0,Route_From)
print(Split_From)

Split_To=np.split(Route_To,partition)
Split_To.insert(0,Route_To)
print(Split_To)
print(sep='\n')

# Initial set up for the indicator matrix
# Use Dis.shape to determine the shape of the zero matrix
# --do not hard code any number
A = np.zeros(Dis.shape)
# Use the length (number) of routes to be evlauated to determine the size of the indicator matrix
# --do not hard code any number
Indicator = np.tile(A,(len(Split_From),1,1))


# Use fancy index to put "1" to the connection where the route goes
# If we pass more than one route, we need to use a "for" loop, unfortunately
for i in range(len(Split_From)):
    Indicator[i,:,:][Split_From[i],Split_To[i]]=1

print("The indicator for the full route and its subroutes are:")
print(Indicator)
print(sep='\n')

#Cost = Dis*Indicator
#print(Dis*Indicator)
Cost = np.sum(np.sum(Dis*Indicator,axis=1),axis=1)
print("The cost for each route is:")
for i in range(len(Cost)):
    print(Cost[i])
print(Cost.shape)
metric=np.array([Cost[0], np.max(Cost[1:])])
print("The total traveling cost is: " + str(metric[0]) + "\n")
print("The longest subroute costs " + str(metric[1]) + " to travel")


[[ 8 15 13  8]
 [22 11 18 11]
 [ 8  7  2 17]
 [11 21 15 26]]

The combined route travels from nodes
[0 2 1 3]
The combined route travels to nodes
[2 1 3 0]

[array([0, 2, 1, 3]), array([0]), array([2, 1]), array([3])]
[array([2, 1, 3, 0]), array([2]), array([1, 3]), array([0])]

The indicator for the full route and its subroutes are:
[[[0. 0. 1. 0.]
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [1. 0. 0. 0.]]]

The cost for each route is:
42.0
13.0
18.0
11.0
(4,)
The total traveling cost is: 42.0

The longest subroute costs 18.0 to travel


In [427]:
# This block is to demondstrate how to calculate the total cost of a given route
# Here we use a metrix to represent the cost of any possible connection among n cities
# The route is reperented as an arrary where the (integer) values of the array represent 
# the index of the node 
# Need to turn this into a function

# Overall approach: 
# 1. We use a square matrix where "1" represent a connection of the given route 
#   and "0" everywhere else
# 2. We then multiply this sparse matrix with the cost/distance matrix
# 3. We sum up the value of all entries of the product. This gives us the toal (traveling) cost of the route 



from scipy import sparse
from scipy.stats import uniform
from array import array
import numpy as np
import random
np.random.seed(2)

row_ind=np.array([0,3,4])
col_ind=np.array([2,0,1])
print("Row index is")
print(row_ind)
print("Col index is")
print(col_ind)
print(sep='\n')


# The floowing block is my attempt to use the "sparse.coo_matrx" funtion for step 1
# It's not sucessful because the subroute we will use in our application will likely
# has indicies all smaller than the size of the distance matrix
# I'm leaving the code here for future reference


#data=np.array(np.repeat(1,(row_ind.size)))

#mat_coo = sparse.coo_matrix((data,(row_ind,col_ind)))
#print(mat_coo.toarray())
#print(sep='\n')
#print(mat_coo.toarray().size)


# This is the end of the sparse matrix appraoch


# It turns out, it's quicker to just use fancy index
a=np.zeros((6,6))
#print(a)
#print(sep='\n')
a[row_ind,col_ind]=1
print(a)
print(np.sum(a))


Row index is
[0 3 4]
Col index is
[2 0 1]

[[0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
3.0


In [374]:
# This block of code is to demonstrate hoe to split an array into a few sub-arrays 
# based on the indicies of its entry
# May worth turning into a (Lambda) function, but can also leave as a line item

import numpy as np

A = np.array ([5.0,6.0,11.0, 4.0,10.0,1.0, 2.0, 12.0 ,7.0,8.0,9.0])

print(A.size)

partition = np.array([3,8])

Split=np.split(A,partition)

print("The number of the sub array is "+ str(len(Split)) + ".")

for i in range(len(Split)):
    print(Split[i])

11
The number of the sub array is 3.
[ 5.  6. 11.]
[ 4. 10.  1.  2. 12.]
[7. 8. 9.]
